# Evaluation config for ELIR dehazing.
# Usage:
#   python eval.py -y configs/elir_eval_dehazing.yaml

env_cfg:
  seed: 2025

dataset_cfg:
  val_dataset:
    name: Paired
    path: ~/moxt/DiffUIR/Datasets/Restoration/Snow100K/test/Snow100K-S
    lq_subdir: lq
    hq_subdir: hq
    patch_size: null
    batch_size: 1
    num_workers: 4
    training: false
    use_latent_cache: false

model_cfg:
  arch_cfg:
    name: elir
    params:
      fm_cfg: {k_steps: 15, sigma_s: 0.1, latent_shape: [16,64,64], seed: 2025,dynamic_noise: false,     # false=静态噪声；true=每次前向随机噪声
               force_static_noise: false
      }
      fmir_cfg:
        name: lunet
        params: {ch_mult: [1,2,1,2], n_mid_blocks: 3, in_channels: 16, hid_channels: 128, out_channels: 16,
                 t_emb_dim: 160, overparametrization: True}
        trainable: false
      mmse_cfg:
        name: rrdbnet
        params: {c_inout: 16, c_hid: 96, n_rrdb: 3, overparametrization: True}
        trainable: false
      enc_cfg:
        name: taesd
        trainable: false
      dec_cfg:
        name: taesd
        trainable: false
    path: /home/a27/moxt/elir_sft/runs/desnow_1/epoch=110-step=660758.ckpt

eval_cfg:
  image_size: 256
  metrics: [psnr, fid, ssim]
  save_images: true
  max_save_images: 4
  out_dir: ./runs/eval_desnow